- id: doi:doi.org/10.1038/s41698-022-00271-x
  image: https://www.nature.com/articles/s41698-022-00271-x/figures/1
  tags:
    - cancer

- id: doi:doi.org/10.1101/gr.256388.119
  image: https://freya.flatironinstitute.org/Hand-Print-and-Paw-Print-Decal.png
  tags:
    - comparative genomics
  repo: https://github.com/flatironinstitute/FREYA

- id: pmid:30864317
  tags:
    - tools
  repo: https://github.com/graim/PLATYPUS

- id: pmid:30322867
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6310008/bin/nihms-1509825-f0001.jpg
  tags:
    - TCGA
   
- id: pmid:29471451
  image: https://www.biorxiv.org/content/biorxiv/early/2017/06/25/154773/F1.large.jpg?width=800&height=600&carousel=1
  tags:
    - comparative genomics
    
- id: pmid:29211761
  image: https://storage.googleapis.com/plos-corpus-prod/10.1371/journal.pone.0170340/1/pone.0170340.g001.PNG_L?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=wombat-sa%40plos-prod.iam.gserviceaccount.com%2F20210607%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20210607T153302Z&X-Goog-Expires=86400&X-Goog-SignedHeaders=host&X-Goog-Signature=165c9d0ca10af63a393c8e7f435831d8f519aa40c783881180e279c112a168534d8755649d4ab7a8a0a6c3844ca5db3bb732dc54969ffc4040856d856feacf9d1dd2815975ba67bec73e6024e112b536e61392143c2b85322446d5105631bb7290dcc0ca4408c128ec9859bbe58090bfdc1ce3ae562b24a0b6f04c81f9dcc392df28e302b373262624f06e8d96923925da89bbb1eb74ed1048cd12c42ed58a0ad26605f9079caa36891b01f7b204e5278c171f029f458bdeddbdcba925394294ce5b9610fa91b7395044468baf614c368f212aa5a1ca5ac66cef235b4305bebeaf7cc1b4eac145a2e43e44d95f79443b397aff156daf49253b73d97cb6446886
  tags:
    - tools
    - competition

- id: pmid:29092953
  image: https://aacrjournals.org/view-large/figure/13373627/e111fig1.jpeg
  tags:
    - tools  
  extra-links:
    - type: source
      link: https://tumormap.ucsc.edu/

- id: pmid:28988802
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5814247/bin/nihms939327f1.jpg
  tags:
    - competition  

- id: pmid:28622513
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867417306396-fx1.jpg
  tags:
    - TCGA

- id: pmid:28359308
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6417802/bin/nihms-999775-f0001.jpg
  tags:
    - tools

- id: pmid:28162975
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5643159/bin/nihms849815f3.jpg
  tags:
    - TCGA

- id: pmid:26901648
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnmeth.3773/MediaObjects/41592_2016_Article_BFnmeth3773_Fig1_HTML.jpg?as=webp
  tags:
    - competition  

- id: pmid:26460041
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/4664352/bin/pnas.1518007112sfig03.jpg
  tags:
    - cancer

- id: pmid:26544944
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867415013392-fx1.jpg
  tags:
    - TCGA

- id: pmid:23514123
    - tools

- id: doi:doi.org/10.1038/nmeth.2340
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnmeth.2340/MediaObjects/41592_2013_Article_BFnmeth2340_Fig1_HTML.jpg?as=webp
  tags:
    - competition  
