- id: doi:doi.org/10.1101/2023.06.28.546898
  image: https://www.biorxiv.org/sites/default/files/bioRxiv_article.jpg
  tags:
    - tools

- id: doi:doi.org/10.1016/j.addr.2023.114974
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0169409X23002892-ga1.jpg
  tags:
    - tools
    - cancer

- id: doi:doi.org/10.1097%2FCCE.0000000000000929
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10270496/figure/F2/
  tags:
    - sepsis

- id: doi:doi.org/10.1097%2FSHK.0000000000001952
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9391290/figure/F1/
  tags:
    - sepsis

- id: doi:doi.org/10.1038/s41698-022-00271-x
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41698-022-00271-x/MediaObjects/41698_2022_271_Fig1_HTML.png?as=webp
  tags:
    - cancer

- id: doi:doi.org/10.1101/gr.256388.119
  image: https://freya.flatironinstitute.org/Hand-Print-and-Paw-Print-Decal.png
  tags:
    - comparative genomics
  repo: https://github.com/flatironinstitute/FREYA

- id: pmid:30864317
  image: https://www.ncbi.nlm.nih.gov/corecgi/tileshop/tileshop.fcgi?p=PMC3&id=124768&s=86&r=1&c=1
  tags:
    - tools
  repo: https://github.com/graim/PLATYPUS

- id: pmid:30322867
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6310008/bin/nihms-1509825-f0001.jpg
  tags:
    - TCGA
   
- id: pmid:29471451
  image: https://www.biorxiv.org/content/biorxiv/early/2017/06/25/154773/F1.large.jpg?width=800&height=600&carousel=1
  tags:
    - comparative genomics
    
- id: pmid:29211761
  image: https://www.ncbi.nlm.nih.gov/corecgi/tileshop/tileshop.fcgi?p=PMC3&id=345551&s=73&r=1&c=4
  tags:
    - tools
    - competition

- id: pmid:29092953
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5751940/bin/nihms930124f1.jpg
  tags:
    - tools  
  extra-links:
    - type: source
      link: https://tumormap.ucsc.edu/

- id: pmid:28988802
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5814247/bin/nihms939327f1.jpg
  tags:
    - competition  

- id: pmid:28622513
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867417306396-fx1.jpg
  tags:
    - TCGA

- id: pmid:28359308
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6417802/bin/nihms-999775-f0001.jpg
  tags:
    - tools

- id: pmid:28162975
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5643159/bin/nihms849815f3.jpg
  tags:
    - TCGA

- id: pmid:26901648
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnmeth.3773/MediaObjects/41592_2016_Article_BFnmeth3773_Fig1_HTML.jpg?as=webp
  tags:
    - competition  

- id: pmid:26460041
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/4664352/bin/pnas.1518007112sfig03.jpg
  tags:
    - cancer

- id: pmid:26544944
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867415013392-fx1.jpg
  tags:
    - TCGA

- id: pmid:23514123
    - tools

- id: doi:doi.org/10.1038/nmeth.2340
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnmeth.2340/MediaObjects/41592_2013_Article_BFnmeth2340_Fig1_HTML.jpg?as=webp
  tags:
    - competition  
