- id: doi:doi.org/10.1101/gr.256388.119
  image: https://freya.flatironinstitute.org/Hand-Print-and-Paw-Print-Decal.png
  tags:
    - comparative genomics
  repo: https://github.com/flatironinstitute/FREYA

- id: pmid:30864317
  tags:
    - tools
  repo: https://github.com/graim/PLATYPUS

- id: pmid:30322867
  tags:
    - TCGA
   
- id: pmid:29471451
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/mbe/35/5/10.1093_molbev_msy018/1/m_msy018f1.png?Expires=1625810485&Signature=Ad-g02h~9m0T-D5SyNfYuCsy8QNHwlk4uUqaJXXdoZC85S8TeIUp~9x2L13ftGv81W0apawzBtc4J9F7bExFGFj5uTjkRRJPxMHl-gTnbd2PgZH6YwljbIh2w3-w848mqG0c0mVrG62pixF7Gmjy5yQNO7kV-UrDt78V~2Zg2nJH1QjQWNk4kOLEc1ZdDsATB5GlFqDWtG5tQ~V7cxBKwKqaNKGjImR9auhmf80~KpeUUuOE03Q6yUQCZ6gREhN3pgBpfCfPAAv9EeU5bFf~oZXlfV4M5s~2SIROqLVOR23nRENFvD4oOVxuDjo7EjkgEn7iBdaPvfTxIQDZwMJnEQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags:
    - comparative genomics
    
- id: pmid:29211761
  image: https://storage.googleapis.com/plos-corpus-prod/10.1371/journal.pone.0170340/1/pone.0170340.g001.PNG_L?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=wombat-sa%40plos-prod.iam.gserviceaccount.com%2F20210607%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20210607T153302Z&X-Goog-Expires=86400&X-Goog-SignedHeaders=host&X-Goog-Signature=165c9d0ca10af63a393c8e7f435831d8f519aa40c783881180e279c112a168534d8755649d4ab7a8a0a6c3844ca5db3bb732dc54969ffc4040856d856feacf9d1dd2815975ba67bec73e6024e112b536e61392143c2b85322446d5105631bb7290dcc0ca4408c128ec9859bbe58090bfdc1ce3ae562b24a0b6f04c81f9dcc392df28e302b373262624f06e8d96923925da89bbb1eb74ed1048cd12c42ed58a0ad26605f9079caa36891b01f7b204e5278c171f029f458bdeddbdcba925394294ce5b9610fa91b7395044468baf614c368f212aa5a1ca5ac66cef235b4305bebeaf7cc1b4eac145a2e43e44d95f79443b397aff156daf49253b73d97cb6446886
  tags:
    - tools
    - competition

- id: pmid:29092953
  tags:
    - tools  
  extra-links:
    - type: source
      link: https://tumormap.ucsc.edu/

- id: pmid:28988802
  tags:
    - competition  

- id: pmid:28622513
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867417306396-fx1.jpg
  tags:
    - TCGA

- id: pmid:28359308
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12920-017-0256-3/MediaObjects/12920_2017_256_Fig1_HTML.gif?as=webp
  tags:
    - tools

- id: pmid:28162975
  tags:
    - TCGA

- id: pmid:26901648
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnmeth.3773/MediaObjects/41592_2016_Article_BFnmeth3773_Fig1_HTML.jpg?as=webp
  tags:
    - competition  

- id: pmid:26460041
  tags:
    - cancer

- id: pmid:26544944
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0092867415013392-fx1.jpg
  tags:
    - TCGA

- id: pmid:23514123
    - tools

- id: doi:doi.org/10.1038/nmeth.2340
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fnmeth.2340/MediaObjects/41592_2013_Article_BFnmeth2340_Fig1_HTML.jpg?as=webp
  tags:
    - competition  
